version: "2"

services:
  eosd:
    build:
      context: .
    image: eosio/eos
    command: /opt/eos/bin/start_eosd.sh
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - ./data-dir/eosd:/opt/eos/bin/data-dir
      - ./config.ini:/opt/eos/bin/data-dir/config.ini

  walletd:
    image: eosio/eos
    command: /opt/eos/bin/eos-walletd
    links:
      - eosd
    volumes:
      - ./data-dir/walletd:/opt/eos/bin/data-dir

volumes:
  eosd-data-volume:
  walletd-data-volume: