#!/bin/bash

# Usage:
# Go into cmd loop: sudo ./eosc.sh
# Run single cmd:  sudo ./eosc.sh <eosc paramers>

PREFIX="docker-compose exec eosd /opt/eos/bin/eosc"
if [ -z $1 ] ; then
  while :
  do
    read -e -p "eosc " cmd
    history -s "$cmd"
    $PREFIX $cmd
  done
else
  $PREFIX $@
fi
