version: "3"

services:
  builder:
    build:
      context: builder
    image: eosio/builder

  nodeos:
    build:
      context: .
    image: eosio/eos_3
    command: /opt/eosio/bin/start_nodeos.sh
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - ./data-dir/nodeos:/opt/eos/bin/data-dir
      - ./config.ini:/opt/eos/bin/data-dir/config.ini
    depends_on:
      - builder

  walletd_3:
    image: eosio/eos_3
    command: /opt/eosio/bin/eosiowd
    links:
      - nodeos
    volumes:
      - ./data-dir/walletd:/opt/eos/bin/data-dir
      