version: "3"

services:
  nodeos:
    build:
      context: .
    image: eosio/eos
    command: /opt/eosio/bin/start_nodeos.sh
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - ./data-dir/nodeos:/opt/eos/bin/data-dir
      - ./config.ini:/opt/eos/bin/data-dir/config.ini

  walletd:
    image: eosio/eos
    command: /opt/eosio/bin/eosiowd
    links:
      - nodeos
    volumes:
      - ./data-dir/walletd:/opt/eos/bin/data-dir
      